# Generated by Django 5.2.5 on 2025-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('sopa', models.CharField(max_length=100)),
                ('contorno', models.CharField(max_length=100)),
                ('seco', models.CharField(max_length=100)),
                ('jugo', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='comida_images/')),
            ],
            options={
                'verbose_name': 'comida',
                'verbose_name_plural': 'comidas',
            },
        ),
    ]
